services:
  sims-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sims-web-app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      # Pass your app UID into the container
      APP_UID: "${APP_UID:-1000}"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    restart: unless-stopped
    working_dir: /app